import { combineReducers } from "redux";
import settings from "./settings";
import demographics from "./demographics";
import user from "./user";
import client from "./client";
import auth from "./auth";
import filter from "./filter";
import {
  userManagementDepartments,
  userManagementLocations,
  userManagementUsers,
  userManagementDomainHeader,
  CampaignBasicBufferAllData,
  CampaignBufferCommentAllData,
  CampaignBufferRatesAllData,
  CampaignCommentAllData,
  CampaignStatsAllData,
  CampaignRatesAllData,
  CampaignBarAllData,
  CampaignHeatAllData,
  CampaignHeatBufferAllData,
  campaignMain,
  campaignMainByID,
  clientsManagement,
  getPreferencesDemographic,
  sendPreferencesDemographic,
  toggleEnableDepartment,
  getLocationFloorData,
  getFloorData,
  helpDeskGetData,
  getlocationGroupList,
  getLocationData,
  locationListData,
  getNotificationManagement,
  exportClients,
  saveClientsMainSettings
} from './adminReducers.js'
import {
  campaignDetailsReducer,
  campaignsGraf,
  campaignsReducer,
  bufferCampaignsReducer,
  feedbackCommentsViewReducer,
  feedbackClientDataViewReducer,
  feedbackJoinDataViewReducer ,
  feedBackResult,
  feedBackThemeView,
  regionsGlobal,
  campaignClosedDetails,
  results,
  waveEngagement,
  xpScore,
  newSurveyHomeReducer
} from './clientReducers'

import {leesmanClient, leesmanLogs, leesmanMigration} from './leesmanReducer'
export default combineReducers({
   
  settings,
  demographics,
  user,
  client,
  clientsManagement,
  auth,
  filter,
  campaignsGraf,
  userManagementDepartments, 
  userManagementLocations, 
  userManagementUsers, 
  userManagementDomainHeader,
  CampaignBasicBufferAllData,
  CampaignBufferCommentAllData,
  CampaignBufferRatesAllData,
  CampaignCommentAllData,
  CampaignStatsAllData,
  CampaignRatesAllData,
  CampaignBarAllData,
  CampaignHeatAllData,
  CampaignHeatBufferAllData,
  campaignDetailsReducer,
  campaignsReducer, 
  bufferCampaignsReducer,
  feedbackCommentsViewReducer,
  feedbackClientDataViewReducer,
  feedbackJoinDataViewReducer,
  feedBackResult,
  feedBackThemeView,
  regionsGlobal,
  campaignClosedDetails,
  results,
  waveEngagement,
  xpScore,
  newSurveyHomeReducer,
  campaignMain,
  campaignMainByID,
  leesmanClient,
  leesmanLogs,
  leesmanMigration,
  getPreferencesDemographic,
  sendPreferencesDemographic,
  toggleEnableDepartment,
  getLocationFloorData,
  getFloorData,
  helpDeskGetData,
  getlocationGroupList,
  getLocationData,
  locationListData,
  getNotificationManagement,
  exportClients,
  saveClientsMainSettings
});
